export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL';

export const PRODUCT_WISHLIST_LOAD_REQUEST = 'PRODUCT_WISHLIST_LOAD_REQUEST';
export const PRODUCT_WISHLIST_LOAD_SUCCESS = 'PRODUCT_WISHLIST_LOAD_SUCCESS';
export const PRODUCT_WISHLIST_LOAD_FAIL = 'PRODUCT_WISHLIST_LOAD_FAIL';

export const PRODUCT_HISTORY_LOAD_REQUEST = 'PRODUCT_HISTORY_LOAD_REQUEST';
export const PRODUCT_HISTORY_LOAD_SUCCESS = 'PRODUCT_HISTORY_LOAD_SUCCESS';
export const PRODUCT_HISTORY_LOAD_FAIL = 'PRODUCT_HISTORY_LOAD_FAIL';

export const PRODUCT_HISTORY_SET_REQUEST = 'PRODUCT_HISTORY_SET_REQUEST';
export const PRODUCT_HISTORY_SET_SUCCESS = 'PRODUCT_HISTORY_SET_SUCCESS';
export const PRODUCT_HISTORY_SET_FAIL = 'PRODUCT_HISTORY_SET_FAIL';
