export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL';

export const PRODUCT_COLLECTIONS_LOAD_REQUEST = 'PRODUCT_COLLECTIONS_LOAD_REQUEST';
export const PRODUCT_COLLECTIONS_LOAD_SUCCESS = 'PRODUCT_COLLECTIONS_LOAD_SUCCESS';
export const PRODUCT_COLLECTIONS_LOAD_FAIL = 'PRODUCT_COLLECTIONS_LOAD_FAIL';

export const PRODUCT_COLLECTIONS_ADD_REQUEST = 'PRODUCT_COLLECTIONS_ADD_REQUEST';
export const PRODUCT_COLLECTIONS_ADD_SUCCESS = 'PRODUCT_COLLECTIONS_ADD_SUCCESS';
export const PRODUCT_COLLECTIONS_ADD_FAIL = 'PRODUCT_COLLECTIONS_ADD_FAIL';
export const PRODUCT_COLLECTIONS_ADD_RESET = 'PRODUCT_COLLECTIONS_ADD_RESET';

export const PRODUCT_COLLECTIONS_UPDATE_REQUEST = 'PRODUCT_COLLECTIONS_UPDATE_REQUEST';
export const PRODUCT_COLLECTIONS_UPDATE_SUCCESS = 'PRODUCT_COLLECTIONS_UPDATE_SUCCESS';
export const PRODUCT_COLLECTIONS_UPDATE_FAIL = 'PRODUCT_COLLECTIONS_UPDATE_FAIL';
export const PRODUCT_COLLECTIONS_UPDATE_RESET = 'PRODUCT_COLLECTIONS_UPDATE_RESET';

export const PRODUCT_COLLECTIONS_REMOVE_REQUEST = 'PRODUCT_COLLECTIONS_REMOVE_REQUEST';
export const PRODUCT_COLLECTIONS_REMOVE_SUCCESS = 'PRODUCT_COLLECTIONS_REMOVE_SUCCESS';
export const PRODUCT_COLLECTIONS_REMOVE_FAIL = 'PRODUCT_COLLECTIONS_REMOVE_FAIL';
export const PRODUCT_COLLECTIONS_REMOVE_RESET = 'PRODUCT_COLLECTIONS_REMOVE_RESET';

export const PRODUCT_WISHLIST_LOAD_REQUEST = 'PRODUCT_WISHLIST_LOAD_REQUEST';
export const PRODUCT_WISHLIST_LOAD_SUCCESS = 'PRODUCT_WISHLIST_LOAD_SUCCESS';
export const PRODUCT_WISHLIST_LOAD_FAIL = 'PRODUCT_WISHLIST_LOAD_FAIL';

export const PRODUCT_WISHLIST_ADD_REQUEST = 'PRODUCT_WISHLIST_ADD_REQUEST';
export const PRODUCT_WISHLIST_ADD_SUCCESS = 'PRODUCT_WISHLIST_ADD_SUCCESS';
export const PRODUCT_WISHLIST_ADD_FAIL = 'PRODUCT_WISHLIST_ADD_FAIL';
export const PRODUCT_WISHLIST_ADD_RESET = 'PRODUCT_WISHLIST_ADD_RESET';

export const PRODUCT_WISHLIST_REMOVE_REQUEST = 'PRODUCT_WISHLIST_REMOVE_REQUEST';
export const PRODUCT_WISHLIST_REMOVE_SUCCESS = 'PRODUCT_WISHLIST_REMOVE_SUCCESS';
export const PRODUCT_WISHLIST_REMOVE_FAIL = 'PRODUCT_WISHLIST_REMOVE_FAIL';
export const PRODUCT_WISHLIST_REMOVE_RESET = 'PRODUCT_WISHLIST_REMOVE_RESET';

export const PRODUCT_HISTORY_LOAD_REQUEST = 'PRODUCT_HISTORY_LOAD_REQUEST';
export const PRODUCT_HISTORY_LOAD_SUCCESS = 'PRODUCT_HISTORY_LOAD_SUCCESS';
export const PRODUCT_HISTORY_LOAD_FAIL = 'PRODUCT_HISTORY_LOAD_FAIL';

export const PRODUCT_HISTORY_SET_REQUEST = 'PRODUCT_HISTORY_SET_REQUEST';
export const PRODUCT_HISTORY_SET_SUCCESS = 'PRODUCT_HISTORY_SET_SUCCESS';
export const PRODUCT_HISTORY_SET_FAIL = 'PRODUCT_HISTORY_SET_FAIL';
